[package]
name = "orbital_elements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
astro = "2.0.0"
regex = "1.6.0"
comment-strip = "0.1.3"

[[bin]]
name = "orbital_elements"
path = "./src/main.rs"
